version: '3'
services:
  twitter_socket:
    build: ./twitter_socket
    ports:
      - 5555:5555

    environment:
      - ACCESS_KEY=$ACCESS_KEY
      - ACCESS_SECRET=$ACCESS_SECRET
      - CONSUMER_KEY=$CONSUMER_KEY
      - CONSUMER_SECRET=$CONSUMER_SECRET
      - TWITTER_PARAM=$TWITTER_PARAM

  spark-master2:
    image: 'bde2020/spark-master:latest'
    volumes:
      - ./dags:/app
    command: '/spark/bin/spark-submit --master local[*] /app/twitter_stream.py'
    ports:
      - 8080:8080
      - 7077:7077

    environment:
      - PYSPARK_PYTHON=python3
      - SPARK_HOME=/spark

  spark-master:
    image: bde2020/spark-master:3.3.0-hadoop3.3
    container_name: spark-master
    depends_on:
      - twitter_socket
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - PYSPARK_PYTHON=python3
      - SPARK_HOME=/spark

  spark-worker-1:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - PYSPARK_PYTHON=python3
      - SPARK_HOME=/spark

networks:
  default:
    external:
      name: serasa
